export { AlertPage } from './alert.page'
export { ButtonDarkPage } from './button-dark.page'
export { ButtonWhitePage } from './button-white.page'
export { ColorsPage as ColorPage } from './colors.page'
export { EditorPage } from './editor.page'
export { EffectPage } from './effect.page'
export { ExtraComponentsPage } from './extra-components.page'
export { FormElementsPage } from './form-elements.page'
export { HomePage } from './home.page'
export { ImagePage } from './image.page'
export { InputPage } from './input.page'
export { OverlaysPage } from './overlays.page'
export { SelectPage } from './select.page'
export { TagsBadgePage } from './tags-badge.page'
export { TextareaPage } from './textarea.page'
export { NotificationPage } from './toast.page'
export { TypographyPage } from './typography.page'
export { IconsPage } from './icons.page'
